/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated.assessments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated.workouts'
import { Route as MediaMediaIdRouteImport } from './routes/media.$mediaId'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated.api.docs'
import { Route as AuthenticatedAssessmentsAssessmentIdRouteImport } from './routes/_authenticated.assessments_.$assessmentId'
import { Route as AuthenticatedWorkoutsWorkoutIdRouteImport } from './routes/_authenticated.workouts_.$workoutId'
import { Route as ApiV1AssessmentsRouteImport } from './routes/api.v1.assessments'
import { Route as ApiV1CapabilityLevelDefinitionsRouteImport } from './routes/api.v1.capability-level-definitions'
import { Route as ApiV1CurrentCapabilityLevelsRouteImport } from './routes/api.v1.current-capability-levels'
import { Route as ApiV1ExerciseCatalogOptionsRouteImport } from './routes/api.v1.exercise-catalog-options'
import { Route as ApiV1ExerciseVariantsRouteImport } from './routes/api.v1.exercise-variants'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api.v1.openapi[.]json'
import { Route as ApiV1WorkoutQueueRouteImport } from './routes/api.v1.workout-queue'
import { Route as ApiV1WorkoutsRouteImport } from './routes/api.v1.workouts'
import { Route as AuthenticatedWorkoutsSessionSessionIdRouteImport } from './routes/_authenticated.workouts_.session.$sessionId'
import { Route as ApiV1AssessmentsAssessmentIdRouteImport } from './routes/api.v1.assessments.$assessmentId'
import { Route as ApiV1ExerciseVariantsVariantIdRouteImport } from './routes/api.v1.exercise-variants.$variantId'
import { Route as ApiV1WorkoutsWorkoutIdRouteImport } from './routes/api.v1.workouts.$workoutId'
import { Route as ApiV1MediaAssetsMediaIdContentRouteImport } from './routes/api.v1.media-assets.$mediaId.content'
import { Route as ApiV1WorkoutsWorkoutIdDuplicateRouteImport } from './routes/api.v1.workouts.$workoutId.duplicate'
import { Route as ApiV1WorkoutsWorkoutIdValidationRouteImport } from './routes/api.v1.workouts.$workoutId.validation'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentsAssessmentIdRoute =
  AuthenticatedAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments_/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkoutsWorkoutIdRoute =
  AuthenticatedWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts_/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1AssessmentsRoute = ApiV1AssessmentsRouteImport.update({
  id: '/api/v1/assessments',
  path: '/api/v1/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CapabilityLevelDefinitionsRoute =
  ApiV1CapabilityLevelDefinitionsRouteImport.update({
    id: '/api/v1/capability-level-definitions',
    path: '/api/v1/capability-level-definitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CurrentCapabilityLevelsRoute =
  ApiV1CurrentCapabilityLevelsRouteImport.update({
    id: '/api/v1/current-capability-levels',
    path: '/api/v1/current-capability-levels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ExerciseCatalogOptionsRoute =
  ApiV1ExerciseCatalogOptionsRouteImport.update({
    id: '/api/v1/exercise-catalog-options',
    path: '/api/v1/exercise-catalog-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ExerciseVariantsRoute = ApiV1ExerciseVariantsRouteImport.update({
  id: '/api/v1/exercise-variants',
  path: '/api/v1/exercise-variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WorkoutQueueRoute = ApiV1WorkoutQueueRouteImport.update({
  id: '/api/v1/workout-queue',
  path: '/api/v1/workout-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WorkoutsRoute = ApiV1WorkoutsRouteImport.update({
  id: '/api/v1/workouts',
  path: '/api/v1/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsSessionSessionIdRoute =
  AuthenticatedWorkoutsSessionSessionIdRouteImport.update({
    id: '/workouts_/session/$sessionId',
    path: '/workouts/session/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1AssessmentsAssessmentIdRoute =
  ApiV1AssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => ApiV1AssessmentsRoute,
  } as any)
const ApiV1ExerciseVariantsVariantIdRoute =
  ApiV1ExerciseVariantsVariantIdRouteImport.update({
    id: '/$variantId',
    path: '/$variantId',
    getParentRoute: () => ApiV1ExerciseVariantsRoute,
  } as any)
const ApiV1WorkoutsWorkoutIdRoute = ApiV1WorkoutsWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => ApiV1WorkoutsRoute,
} as any)
const ApiV1MediaAssetsMediaIdContentRoute =
  ApiV1MediaAssetsMediaIdContentRouteImport.update({
    id: '/api/v1/media-assets/$mediaId/content',
    path: '/api/v1/media-assets/$mediaId/content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkoutsWorkoutIdDuplicateRoute =
  ApiV1WorkoutsWorkoutIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => ApiV1WorkoutsWorkoutIdRoute,
  } as any)
const ApiV1WorkoutsWorkoutIdValidationRoute =
  ApiV1WorkoutsWorkoutIdValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => ApiV1WorkoutsWorkoutIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/api/docs': typeof AuthenticatedApiDocsRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/current-capability-levels': typeof ApiV1CurrentCapabilityLevelsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/workout-queue': typeof ApiV1WorkoutQueueRoute
  '/api/v1/workouts': typeof ApiV1WorkoutsRouteWithChildren
  '/workouts/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/workouts/$workoutId': typeof ApiV1WorkoutsWorkoutIdRouteWithChildren
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
  '/api/v1/workouts/$workoutId/duplicate': typeof ApiV1WorkoutsWorkoutIdDuplicateRoute
  '/api/v1/workouts/$workoutId/validation': typeof ApiV1WorkoutsWorkoutIdValidationRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/docs': typeof AuthenticatedApiDocsRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/current-capability-levels': typeof ApiV1CurrentCapabilityLevelsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/workout-queue': typeof ApiV1WorkoutQueueRoute
  '/api/v1/workouts': typeof ApiV1WorkoutsRouteWithChildren
  '/workouts/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/workouts/$workoutId': typeof ApiV1WorkoutsWorkoutIdRouteWithChildren
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
  '/api/v1/workouts/$workoutId/duplicate': typeof ApiV1WorkoutsWorkoutIdDuplicateRoute
  '/api/v1/workouts/$workoutId/validation': typeof ApiV1WorkoutsWorkoutIdValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/api/docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/assessments_/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/_authenticated/workouts_/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/current-capability-levels': typeof ApiV1CurrentCapabilityLevelsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/workout-queue': typeof ApiV1WorkoutQueueRoute
  '/api/v1/workouts': typeof ApiV1WorkoutsRouteWithChildren
  '/_authenticated/workouts_/session/$sessionId': typeof AuthenticatedWorkoutsSessionSessionIdRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/workouts/$workoutId': typeof ApiV1WorkoutsWorkoutIdRouteWithChildren
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
  '/api/v1/workouts/$workoutId/duplicate': typeof ApiV1WorkoutsWorkoutIdDuplicateRoute
  '/api/v1/workouts/$workoutId/validation': typeof ApiV1WorkoutsWorkoutIdValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/login'
    | '/assessments'
    | '/settings'
    | '/workouts'
    | '/media/$mediaId'
    | '/api/docs'
    | '/assessments/$assessmentId'
    | '/workouts/$workoutId'
    | '/api/v1/assessments'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/current-capability-levels'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/workout-queue'
    | '/api/v1/workouts'
    | '/workouts/session/$sessionId'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/workouts/$workoutId'
    | '/api/v1/media-assets/$mediaId/content'
    | '/api/v1/workouts/$workoutId/duplicate'
    | '/api/v1/workouts/$workoutId/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/login'
    | '/assessments'
    | '/settings'
    | '/workouts'
    | '/media/$mediaId'
    | '/'
    | '/api/docs'
    | '/assessments/$assessmentId'
    | '/workouts/$workoutId'
    | '/api/v1/assessments'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/current-capability-levels'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/workout-queue'
    | '/api/v1/workouts'
    | '/workouts/session/$sessionId'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/workouts/$workoutId'
    | '/api/v1/media-assets/$mediaId/content'
    | '/api/v1/workouts/$workoutId/duplicate'
    | '/api/v1/workouts/$workoutId/validation'
  id:
    | '__root__'
    | '/_authenticated'
    | '/healthz'
    | '/login'
    | '/_authenticated/assessments'
    | '/_authenticated/settings'
    | '/_authenticated/workouts'
    | '/media/$mediaId'
    | '/_authenticated/'
    | '/_authenticated/api/docs'
    | '/_authenticated/assessments_/$assessmentId'
    | '/_authenticated/workouts_/$workoutId'
    | '/api/v1/assessments'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/current-capability-levels'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/workout-queue'
    | '/api/v1/workouts'
    | '/_authenticated/workouts_/session/$sessionId'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/workouts/$workoutId'
    | '/api/v1/media-assets/$mediaId/content'
    | '/api/v1/workouts/$workoutId/duplicate'
    | '/api/v1/workouts/$workoutId/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
  ApiV1AssessmentsRoute: typeof ApiV1AssessmentsRouteWithChildren
  ApiV1CapabilityLevelDefinitionsRoute: typeof ApiV1CapabilityLevelDefinitionsRoute
  ApiV1CurrentCapabilityLevelsRoute: typeof ApiV1CurrentCapabilityLevelsRoute
  ApiV1ExerciseCatalogOptionsRoute: typeof ApiV1ExerciseCatalogOptionsRoute
  ApiV1ExerciseVariantsRoute: typeof ApiV1ExerciseVariantsRouteWithChildren
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1WorkoutQueueRoute: typeof ApiV1WorkoutQueueRoute
  ApiV1WorkoutsRoute: typeof ApiV1WorkoutsRouteWithChildren
  ApiV1MediaAssetsMediaIdContentRoute: typeof ApiV1MediaAssetsMediaIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api/docs': {
      id: '/_authenticated/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments_/$assessmentId': {
      id: '/_authenticated/assessments_/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workouts_/$workoutId': {
      id: '/_authenticated/workouts_/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof AuthenticatedWorkoutsWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/assessments': {
      id: '/api/v1/assessments'
      path: '/api/v1/assessments'
      fullPath: '/api/v1/assessments'
      preLoaderRoute: typeof ApiV1AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/capability-level-definitions': {
      id: '/api/v1/capability-level-definitions'
      path: '/api/v1/capability-level-definitions'
      fullPath: '/api/v1/capability-level-definitions'
      preLoaderRoute: typeof ApiV1CapabilityLevelDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/current-capability-levels': {
      id: '/api/v1/current-capability-levels'
      path: '/api/v1/current-capability-levels'
      fullPath: '/api/v1/current-capability-levels'
      preLoaderRoute: typeof ApiV1CurrentCapabilityLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercise-catalog-options': {
      id: '/api/v1/exercise-catalog-options'
      path: '/api/v1/exercise-catalog-options'
      fullPath: '/api/v1/exercise-catalog-options'
      preLoaderRoute: typeof ApiV1ExerciseCatalogOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercise-variants': {
      id: '/api/v1/exercise-variants'
      path: '/api/v1/exercise-variants'
      fullPath: '/api/v1/exercise-variants'
      preLoaderRoute: typeof ApiV1ExerciseVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workout-queue': {
      id: '/api/v1/workout-queue'
      path: '/api/v1/workout-queue'
      fullPath: '/api/v1/workout-queue'
      preLoaderRoute: typeof ApiV1WorkoutQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workouts': {
      id: '/api/v1/workouts'
      path: '/api/v1/workouts'
      fullPath: '/api/v1/workouts'
      preLoaderRoute: typeof ApiV1WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts_/session/$sessionId': {
      id: '/_authenticated/workouts_/session/$sessionId'
      path: '/workouts/session/$sessionId'
      fullPath: '/workouts/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedWorkoutsSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/assessments/$assessmentId': {
      id: '/api/v1/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/api/v1/assessments/$assessmentId'
      preLoaderRoute: typeof ApiV1AssessmentsAssessmentIdRouteImport
      parentRoute: typeof ApiV1AssessmentsRoute
    }
    '/api/v1/exercise-variants/$variantId': {
      id: '/api/v1/exercise-variants/$variantId'
      path: '/$variantId'
      fullPath: '/api/v1/exercise-variants/$variantId'
      preLoaderRoute: typeof ApiV1ExerciseVariantsVariantIdRouteImport
      parentRoute: typeof ApiV1ExerciseVariantsRoute
    }
    '/api/v1/workouts/$workoutId': {
      id: '/api/v1/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/api/v1/workouts/$workoutId'
      preLoaderRoute: typeof ApiV1WorkoutsWorkoutIdRouteImport
      parentRoute: typeof ApiV1WorkoutsRoute
    }
    '/api/v1/media-assets/$mediaId/content': {
      id: '/api/v1/media-assets/$mediaId/content'
      path: '/api/v1/media-assets/$mediaId/content'
      fullPath: '/api/v1/media-assets/$mediaId/content'
      preLoaderRoute: typeof ApiV1MediaAssetsMediaIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workouts/$workoutId/duplicate': {
      id: '/api/v1/workouts/$workoutId/duplicate'
      path: '/duplicate'
      fullPath: '/api/v1/workouts/$workoutId/duplicate'
      preLoaderRoute: typeof ApiV1WorkoutsWorkoutIdDuplicateRouteImport
      parentRoute: typeof ApiV1WorkoutsWorkoutIdRoute
    }
    '/api/v1/workouts/$workoutId/validation': {
      id: '/api/v1/workouts/$workoutId/validation'
      path: '/validation'
      fullPath: '/api/v1/workouts/$workoutId/validation'
      preLoaderRoute: typeof ApiV1WorkoutsWorkoutIdValidationRouteImport
      parentRoute: typeof ApiV1WorkoutsWorkoutIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedAssessmentsAssessmentIdRoute: typeof AuthenticatedAssessmentsAssessmentIdRoute
  AuthenticatedWorkoutsWorkoutIdRoute: typeof AuthenticatedWorkoutsWorkoutIdRoute
  AuthenticatedWorkoutsSessionSessionIdRoute: typeof AuthenticatedWorkoutsSessionSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedAssessmentsAssessmentIdRoute:
    AuthenticatedAssessmentsAssessmentIdRoute,
  AuthenticatedWorkoutsWorkoutIdRoute: AuthenticatedWorkoutsWorkoutIdRoute,
  AuthenticatedWorkoutsSessionSessionIdRoute:
    AuthenticatedWorkoutsSessionSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiV1AssessmentsRouteChildren {
  ApiV1AssessmentsAssessmentIdRoute: typeof ApiV1AssessmentsAssessmentIdRoute
}

const ApiV1AssessmentsRouteChildren: ApiV1AssessmentsRouteChildren = {
  ApiV1AssessmentsAssessmentIdRoute: ApiV1AssessmentsAssessmentIdRoute,
}

const ApiV1AssessmentsRouteWithChildren =
  ApiV1AssessmentsRoute._addFileChildren(ApiV1AssessmentsRouteChildren)

interface ApiV1ExerciseVariantsRouteChildren {
  ApiV1ExerciseVariantsVariantIdRoute: typeof ApiV1ExerciseVariantsVariantIdRoute
}

const ApiV1ExerciseVariantsRouteChildren: ApiV1ExerciseVariantsRouteChildren = {
  ApiV1ExerciseVariantsVariantIdRoute: ApiV1ExerciseVariantsVariantIdRoute,
}

const ApiV1ExerciseVariantsRouteWithChildren =
  ApiV1ExerciseVariantsRoute._addFileChildren(
    ApiV1ExerciseVariantsRouteChildren,
  )

interface ApiV1WorkoutsWorkoutIdRouteChildren {
  ApiV1WorkoutsWorkoutIdDuplicateRoute: typeof ApiV1WorkoutsWorkoutIdDuplicateRoute
  ApiV1WorkoutsWorkoutIdValidationRoute: typeof ApiV1WorkoutsWorkoutIdValidationRoute
}

const ApiV1WorkoutsWorkoutIdRouteChildren: ApiV1WorkoutsWorkoutIdRouteChildren =
  {
    ApiV1WorkoutsWorkoutIdDuplicateRoute: ApiV1WorkoutsWorkoutIdDuplicateRoute,
    ApiV1WorkoutsWorkoutIdValidationRoute:
      ApiV1WorkoutsWorkoutIdValidationRoute,
  }

const ApiV1WorkoutsWorkoutIdRouteWithChildren =
  ApiV1WorkoutsWorkoutIdRoute._addFileChildren(
    ApiV1WorkoutsWorkoutIdRouteChildren,
  )

interface ApiV1WorkoutsRouteChildren {
  ApiV1WorkoutsWorkoutIdRoute: typeof ApiV1WorkoutsWorkoutIdRouteWithChildren
}

const ApiV1WorkoutsRouteChildren: ApiV1WorkoutsRouteChildren = {
  ApiV1WorkoutsWorkoutIdRoute: ApiV1WorkoutsWorkoutIdRouteWithChildren,
}

const ApiV1WorkoutsRouteWithChildren = ApiV1WorkoutsRoute._addFileChildren(
  ApiV1WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
  ApiV1AssessmentsRoute: ApiV1AssessmentsRouteWithChildren,
  ApiV1CapabilityLevelDefinitionsRoute: ApiV1CapabilityLevelDefinitionsRoute,
  ApiV1CurrentCapabilityLevelsRoute: ApiV1CurrentCapabilityLevelsRoute,
  ApiV1ExerciseCatalogOptionsRoute: ApiV1ExerciseCatalogOptionsRoute,
  ApiV1ExerciseVariantsRoute: ApiV1ExerciseVariantsRouteWithChildren,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1WorkoutQueueRoute: ApiV1WorkoutQueueRoute,
  ApiV1WorkoutsRoute: ApiV1WorkoutsRouteWithChildren,
  ApiV1MediaAssetsMediaIdContentRoute: ApiV1MediaAssetsMediaIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
