/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as MediaMediaIdRouteImport } from './routes/media.$mediaId'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated.api.docs'
import { Route as ApiV1CapabilityLevelDefinitionsRouteImport } from './routes/api.v1.capability-level-definitions'
import { Route as ApiV1ExerciseCatalogOptionsRouteImport } from './routes/api.v1.exercise-catalog-options'
import { Route as ApiV1ExerciseVariantsRouteImport } from './routes/api.v1.exercise-variants'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api.v1.openapi[.]json'
import { Route as ApiV1ExerciseVariantsVariantIdRouteImport } from './routes/api.v1.exercise-variants.$variantId'
import { Route as ApiV1MediaAssetsMediaIdContentRouteImport } from './routes/api.v1.media-assets.$mediaId.content'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiV1CapabilityLevelDefinitionsRoute =
  ApiV1CapabilityLevelDefinitionsRouteImport.update({
    id: '/api/v1/capability-level-definitions',
    path: '/api/v1/capability-level-definitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ExerciseCatalogOptionsRoute =
  ApiV1ExerciseCatalogOptionsRouteImport.update({
    id: '/api/v1/exercise-catalog-options',
    path: '/api/v1/exercise-catalog-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ExerciseVariantsRoute = ApiV1ExerciseVariantsRouteImport.update({
  id: '/api/v1/exercise-variants',
  path: '/api/v1/exercise-variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExerciseVariantsVariantIdRoute =
  ApiV1ExerciseVariantsVariantIdRouteImport.update({
    id: '/$variantId',
    path: '/$variantId',
    getParentRoute: () => ApiV1ExerciseVariantsRoute,
  } as any)
const ApiV1MediaAssetsMediaIdContentRoute =
  ApiV1MediaAssetsMediaIdContentRouteImport.update({
    id: '/api/v1/media-assets/$mediaId/content',
    path: '/api/v1/media-assets/$mediaId/content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/api/docs': typeof AuthenticatedApiDocsRoute
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/docs': typeof AuthenticatedApiDocsRoute
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/api/docs': typeof AuthenticatedApiDocsRoute
  '/api/v1/capability-level-definitions': typeof ApiV1CapabilityLevelDefinitionsRoute
  '/api/v1/exercise-catalog-options': typeof ApiV1ExerciseCatalogOptionsRoute
  '/api/v1/exercise-variants': typeof ApiV1ExerciseVariantsRouteWithChildren
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/exercise-variants/$variantId': typeof ApiV1ExerciseVariantsVariantIdRoute
  '/api/v1/media-assets/$mediaId/content': typeof ApiV1MediaAssetsMediaIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/login'
    | '/settings'
    | '/media/$mediaId'
    | '/api/docs'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/media-assets/$mediaId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/login'
    | '/settings'
    | '/media/$mediaId'
    | '/'
    | '/api/docs'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/media-assets/$mediaId/content'
  id:
    | '__root__'
    | '/_authenticated'
    | '/healthz'
    | '/login'
    | '/_authenticated/settings'
    | '/media/$mediaId'
    | '/_authenticated/'
    | '/_authenticated/api/docs'
    | '/api/v1/capability-level-definitions'
    | '/api/v1/exercise-catalog-options'
    | '/api/v1/exercise-variants'
    | '/api/v1/openapi.json'
    | '/api/v1/exercise-variants/$variantId'
    | '/api/v1/media-assets/$mediaId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
  ApiV1CapabilityLevelDefinitionsRoute: typeof ApiV1CapabilityLevelDefinitionsRoute
  ApiV1ExerciseCatalogOptionsRoute: typeof ApiV1ExerciseCatalogOptionsRoute
  ApiV1ExerciseVariantsRoute: typeof ApiV1ExerciseVariantsRouteWithChildren
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1MediaAssetsMediaIdContentRoute: typeof ApiV1MediaAssetsMediaIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api/docs': {
      id: '/_authenticated/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/capability-level-definitions': {
      id: '/api/v1/capability-level-definitions'
      path: '/api/v1/capability-level-definitions'
      fullPath: '/api/v1/capability-level-definitions'
      preLoaderRoute: typeof ApiV1CapabilityLevelDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercise-catalog-options': {
      id: '/api/v1/exercise-catalog-options'
      path: '/api/v1/exercise-catalog-options'
      fullPath: '/api/v1/exercise-catalog-options'
      preLoaderRoute: typeof ApiV1ExerciseCatalogOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercise-variants': {
      id: '/api/v1/exercise-variants'
      path: '/api/v1/exercise-variants'
      fullPath: '/api/v1/exercise-variants'
      preLoaderRoute: typeof ApiV1ExerciseVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercise-variants/$variantId': {
      id: '/api/v1/exercise-variants/$variantId'
      path: '/$variantId'
      fullPath: '/api/v1/exercise-variants/$variantId'
      preLoaderRoute: typeof ApiV1ExerciseVariantsVariantIdRouteImport
      parentRoute: typeof ApiV1ExerciseVariantsRoute
    }
    '/api/v1/media-assets/$mediaId/content': {
      id: '/api/v1/media-assets/$mediaId/content'
      path: '/api/v1/media-assets/$mediaId/content'
      fullPath: '/api/v1/media-assets/$mediaId/content'
      preLoaderRoute: typeof ApiV1MediaAssetsMediaIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiV1ExerciseVariantsRouteChildren {
  ApiV1ExerciseVariantsVariantIdRoute: typeof ApiV1ExerciseVariantsVariantIdRoute
}

const ApiV1ExerciseVariantsRouteChildren: ApiV1ExerciseVariantsRouteChildren = {
  ApiV1ExerciseVariantsVariantIdRoute: ApiV1ExerciseVariantsVariantIdRoute,
}

const ApiV1ExerciseVariantsRouteWithChildren =
  ApiV1ExerciseVariantsRoute._addFileChildren(
    ApiV1ExerciseVariantsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
  ApiV1CapabilityLevelDefinitionsRoute: ApiV1CapabilityLevelDefinitionsRoute,
  ApiV1ExerciseCatalogOptionsRoute: ApiV1ExerciseCatalogOptionsRoute,
  ApiV1ExerciseVariantsRoute: ApiV1ExerciseVariantsRouteWithChildren,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1MediaAssetsMediaIdContentRoute: ApiV1MediaAssetsMediaIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
